#! /bin/zsh
set -euo pipefail

#echo "Running git-gc on AUR repos"
#for f ($(fd --type d --max-depth 1 . ~/.cache/yay)) { echo "\t$f"; sh -c "cd $f; git gc" >/dev/null 2>&1 }
echo "Moving yay packages to the cache"
sudo find ~/.cache/yay -type f \( -name '*.pkg.tar.xz' -or -name '*.pkg.tar.zst' \) \
        -exec mv -iv {} /var/cache/pacman/pkg/ \;
echo "Cleaning archives out of the yay cache"
find ~/.cache/yay -type f \( -name '*.tar.*' -or -name '*.deb' \) \
    -exec rm -v {} + || true
echo "Cleaning up cache"
paccache -vr
paccache -vruk0
echo "Running pacdiff"
sudo DIFFSEARCHPATH="/boot /etc /usr" DIFFPROG="meld" pacdiff
