#! /bin/zsh
set -e

echo "Running git-gc on AUR repos"
for f (~/.cache/pacaur/*) { echo "\t$f"; sh -c "cd $f; git gc" >/dev/null 2>&1 }
echo "Moving pacaur packages to the cache"
sudo find ~/.cache/pacaur -type f -name '*.pkg.tar.xz' -exec mv -iv {} /var/cache/pacman/pkg/ \;
echo "Cleaning up cache"
paccache -vr
paccache -vruk0
echo "Running pacdiff"
sudo DIFFSEARCHPATH="/boot /etc /usr" DIFFPROG="meld" pacdiff
