#!/bin/zsh

# Encodes video with x265 `-crf 22 -preset slow`,
# Output is a file of the same name in the current directory.

set -euo pipefail

from="$1"
to="${1:t}"

echo "$from -> $to"
ffmpeg -i "$from" -map 0 -c:s copy -c:a copy -c:v hevc -preset slow -crf 22 "$to"
