#!/bin/bash

 #*******************************
 # Multiple dropbox instances
 #*******************************

 dropboxes=(.dropbox-personal .dropbox-blackbird)

 for dropbox in ${dropboxes[@]}; do
     if ! [ -d $HOME/$dropbox ];then
         mkdir $HOME/$dropbox
     fi
     HOME=$HOME/$dropbox/ /opt/dropbox/dropbox start -i &
 done
